version: 2
controller: {}
workers:
  -
    type: router
    options:
      pythonpath:
        - ..
    realms:
      -
        name: realm1
        roles:
          -
            name: anonymous
            permissions:
              -
                uri: ""
                match: prefix
                allow:
                  call: true
                  publish: true
                  register: true
                  subscribe: true
                disclose:
                  caller: false
                  publisher: false
                cache: true
    transports:
      -
        type: web
        endpoint:
          type: tcp
          port: 8080
        paths:
          /:
            type: wsgi
            module: dist.wsgi
            object: application
          static:
            type: static
            directory: ../dist/static/
          ws:
            type: websocket
  -
    type: guest
    executable: python
    arguments:
      - -m
      - fetsy.database
    options:
      workdir: ..
      watch:
        directories:
          - ../fetsy/database
        action: restart
