version: 2
controller: {}
workers:
  -
    type: router
    realms:
      -
        name: realm1
        roles:
          -
            name: anonymous
            permissions:
              -
                uri: ""
                match: prefix
                allow:
                  call: true
                  publish: true
                  register: true
                  subscribe: true
                disclose:
                  caller: false
                  publisher: false
                cache: true
    transports:
      -
        type: web
        endpoint:
          type: tcp
          port: 8080
        paths:
          /:
            type: static
            directory: ../dist/
          ws:
            type: websocket
  -
    type: guest
    executable: python
    arguments:
      - fetsy/database/app.py
    options:
      workdir: ".."
      watch:
        directories:
          - "../fetsy/database"
        action: "restart"
